### ISSUE TITLE
Switch on HTTPS

### ISSUE THREAD

**Issue by stefanw** [okfde/000000.limited#1]
GitHub Pages allows HTTPS for custom domains. Please switch it on in  the settings.

@arnese @streiten: also we should transfer this repo to the okfde org.

**Comment by streiten** [comment]
currently it says: 

> Enforce HTTPS — Unavailable for your site because your domain is not properly configured to support HTTPS 

not sure it thats it but as stated [here](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) the IP adress for the A record needs to be updatet to one of [those].(https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)
let me know if i should transfer it to ofkde right away or we fix https first

**Comment by stefanw** [comment]
A transfer to the okfde org would be good.

**Comment by streiten** [comment]
sure, gh says permission to create repos for okfde is missing

**Comment by stefanw** [comment]
Alright, I made you temporarily an owner of the org (apparently the only way).

**Comment by streiten** [comment]
ok, its there now you can revoke ownership

**Comment by stefanw** [comment]
After a short roundtrip with GitHub support, https is now on.
